### ISSUE TITLE
Testing Scene

### ISSUE THREAD

**Issue by rever96** [RTUITLab/Oculus-HandTracking-Keyboard#1]
Hello, I've just found this project.
Downloaded and opened with Unity. from Project Settings I added the XR Plugin Management and checked Oculus.
Testing the Sample Scene I noticed there are no hands. Maybe some model is missing?

**Comment by Eloren1** [comment]
Hello, @rever96! This project was made for Oculus Quest devices with Oculus plugin. Unlinke SteamVR plugin, you can't emulate hands in the Unity Editor, so you need to build an apk for Quest device.  Hands will be visible in the build.
